language: r
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: o+5bGzGXsuW36RyNEVS1BH0/v97LVRISWbJJs27X1qy66PLLqilAVmWESSWNz0AlQ9HZ8VVXoH9ips/y1Xs5hdng7UaiYayTqDi0r5wRU5dNIDEfLAk29xOebr2BsMbxulyX3SbyK7O5Ma0vWFpu5OuyAnBdSKKtlnvUDG5WYRyjEnXfpTdQmir/M3pGsOio86cgjTTPiA5tMUy7HmSOQ8onVf3EvBI9wiajudZgpvK00JI/oBca9DDTEDf3dgfEs/lxE70zSBEJCPGSnxpJ8uMYy+UjGeq2YiyBovbiWpxJxneXiMn1AlHcB3o30Q7P7j7zUagTSAx21GHcUyJU+z9RtmMtTbQAhrsiAgW0whiRmLcPxYmWh2QmOkG8EEO+v/16XERuQ/MbuV1EMTxUAbZhHetbTCXAJUAkgAjad9m/f5MvknBThrpLLJkkBOK959K6qi1E0kUnetzfQna0VQZC7DYNlILBZpht1WKAUXSrC4oaz0PnmFjtsAM6mRp6SJWwnB7qxDWpAdZ5a3lmKnB6FtSDf/hXHKs3BY7V+mq2ziSMi6mcEN9l/vIHCAP6ZoNJ24VVJcngoRLN90+bYKVq29IdUhdDY0GIrlblZCNZWsC/q9+FBJS5fX7Y8+1iHFdyYApWtm3NRt0socTciJr4FmSZDJ9dDZTBYexiNaM=
